#!/bin/sh
#
# Utility script to generate a wrapper Makefile in the root of the project
# build output directory, to allow direct use of make.
#
# Args:
# $1 - Src directory
# $2 - Output directory
#
# Based on Buildroot's mkmakefile support script:
# https://git.busybox.net/buildroot/tree/support/scripts/mkmakefile
#

MAKEFILE_PATH=$2/Makefile

# Do not regenerate Makefile if readable and owned by effective user id.
[ -r "${MAKEFILE_PATH}" ] && [ -O "${MAKEFILE_PATH}" ] && exit 0

# Prevent overwriting the wrong Makefile.
[ -e "${MAKEFILE_PATH}" ] \
&& ! head -n 1 "${MAKEFILE_PATH}" | grep -qs '# Automatically' \
&& exit 0

printf "  GEN     %s\n" "${MAKEFILE_PATH}"

cat << EOF > "${MAKEFILE_PATH}"
# Automatically generated by $0 for out-of-tree build: don't edit!

ifeq ("\$(origin V)", "command line")
  VERBOSE := \$(V)
endif
ifneq (\$(VERBOSE),1)
  Q := @
endif

makedir := \$(dir \$(lastword \$(MAKEFILE_LIST)))

MAKEARGS := -C "$1"

# If \$(makedir) is not absolute, prefix the path with \$(CURDIR).
# Additionally, remove any trailing '/'.
MAKEARGS += O=\$(if \$(patsubst /%,,\$(makedir)),\$(CURDIR)/)\$(patsubst %/,%,\$(makedir))

MAKEFLAGS += --no-print-directory

.PHONY: _all \$(MAKECMDGOALS)

all := \$(filter-out Makefile,\$(MAKECMDGOALS))

_all:
	\$(Q)umask 0022 && \$(MAKE) \$(MAKEARGS) \$(all)

Makefile:;

\$(all): _all
	@:

%/: _all
	@:
EOF
