ROOTFS_BR2EXT_DIR = $(ROOTFS_PKGDIR)/br2-external
ROOTFS_KCONFIG_FILE = $(ROOTFS_BR2EXT_DIR)/configs/$(call qstrip,$(PRJ_ROOTFS_DEFCONFIG))_defconfig

ROOTFS_MAKE_ENV = BR_TOOLCHAIN_PATH=$(call qstrip,$(PRJ_TOOLCHAIN_PATH))

define ROOTFS_KCONFIG_FIXUP_CMDS
	$(call KCONFIG_SET_OPT,BR2_TOOLCHAIN_EXTERNAL_PATH,"$${BR_TOOLCHAIN_PATH}")
endef

$(eval $(buildroot-component))
