#!/bin/sh

# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev
#/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys

echo "Starting ffmpeg" > /dev/console
#ffmpeg -t  10 -f video4linux2 -video_size 432x240 -input_format mjpeg -i /dev/video0 -pix_fmt rgb565le -f fbdev /dev/fb0 >/dev/console 2>&1
#ffmpeg -t 0.1 -f video4linux2 -video_size 432x240 -input_format mjpeg -i /dev/video0 -pix_fmt rgb565le -f fbdev /dev/fb0 >/dev/console 2>&1
 ffmpeg        -f video4linux2 -video_size 432x240 -input_format mjpeg -i /dev/video0 -frames:v 1 -pix_fmt rgb565le -f fbdev /dev/fb0 >/dev/console 2>&1

exec /bin/sh "$@"
